#!/bin/bash

DEBUG=$1
ZTS=$2
CLANG=$3

FLAGS=" --with-curl \
    --with-zlib \
    --with-pcre-jit \
    --enable-calendar \
    --with-ffi \
    --enable-intl \
    --enable-pcntl \
    --enable-sockets \
    --with-ldap \
    --with-sodium \
    --with-password-argon2 \
    --enable-sysvshm \
    --with-xsl \
    --enable-mysqlnd \
    --enable-shmop \
    --with-readline \
    --enable-mbstring \
    --enable-bcmath \
    --with-openssl \
    --enable-fpm \
    --with-gmp \
    --with-enchant \
    --enable-exif  \
    --enable-gd \
    --with-webp \
    --with-jpeg \
    --with-freetype \
    --with-gettext \
    --with-mysqli \
    --with-pdo-mysql \
    --with-pdo-pgsql \
    --with-pgsql \
    --with-xsl \
    --with-pear \
"

if [ "$DEBUG" == "1" ]; then
    FLAGS="$FLAGS --enable-debug --with-valgrind --enable-phpdbg"
fi

if [ "$ZTS" == "1" ]; then
    FLAGS="$FLAGS --enable-zts"
fi

if [ "$CLANG" == "1" ]; then
    FLAGS="$FLAGS --with-pic"
fi

./configure $FLAGS
